/* Starter recipes from Tom's "Meals Cheat Sheet". Quantities are for 2 people.
   Ingredient format: qty|unit|name|aisle   (aisle: v veg/fruit, m meat/fish, d dairy/eggs, t tins/dry, s spices/sauces, f frozen, b bakery, o other)
   Macros are rough per-serving estimates: cal, protein, carbs, fat. All editable in the app. */
(function () {
  var AISLE = { v: 'Fruit & veg', m: 'Meat & fish', d: 'Dairy & eggs', t: 'Tins & dry', s: 'Spices & sauces', f: 'Frozen', b: 'Bakery', o: 'Other' };
  var rows = [
    // ---------- MEAT ----------
    ['steak', 'Steak, chips & salad', 'Meat', 'Dinner', 30, 'Easy', 720, 48, 45, 36, '2||Sirloin steaks|m;500|g|Potatoes|v;1||Salad bag|v;2||Tomatoes|v;2|tbsp|Olive oil|t;1|knob|Butter|d;2||Garlic cloves|v', 'Cut chips, toss in oil and roast at 220C for 35 min || Take steaks out of the fridge 20 min before, season well || Fry in a very hot pan 2-3 min each side, add butter and garlic and baste || Rest 5 min, serve with chips and salad'],
    ['marry-me-chicken', 'Marry me chicken', 'Meat', 'Dinner', 35, 'Medium', 610, 45, 12, 41, '2||Chicken breasts|m;1|tbsp|Tomato purée|t;150|ml|Double cream|d;100|g|Sundried tomatoes|t;3||Garlic cloves|v;100|ml|Chicken stock|t;30|g|Parmesan|d;1|tsp|Italian herbs|s', 'Season and sear chicken 5 min per side, set aside || Fry garlic and tomato purée for 1 min || Add stock, cream, sundried tomatoes, herbs and parmesan, simmer 5 min || Return chicken, simmer until cooked through (about 10 min) and serve with rice or pasta'],
    ['teriyaki-chicken', 'Teriyaki chicken & rice', 'Meat', 'Dinner', 30, 'Easy', 540, 42, 55, 14, '3||Chicken thighs|m;4|tbsp|Teriyaki sauce|s;150|g|Rice|t;1||Broccoli|v;2||Spring onions|v;1|tsp|Sesame seeds|t', 'Cook the rice || Fry chicken until golden, 8 min || Add teriyaki sauce and cook until sticky, 4 min || Steam the broccoli, serve over rice with spring onion and sesame'],
    ['parma-boursin-chicken', 'Chicken in Parma ham & Boursin', 'Meat', 'Dinner', 40, 'Medium', 560, 46, 3, 40, '2||Chicken breasts|m;1||Boursin (garlic & herb)|d;6||Slices Parma ham|m;300|g|New potatoes|v;150|g|Green beans|v;1|tbsp|Olive oil|t', 'Slice a pocket in each chicken breast and stuff with Boursin || Wrap each in 3 slices Parma ham || Roast at 200C for 30 min until cooked through || Boil potatoes and beans and serve'],
    ['devilled-chicken', 'Devilled chicken', 'Meat', 'Dinner', 40, 'Medium', 520, 44, 18, 28, '3||Chicken thighs|m;2|tbsp|Worcestershire sauce|s;1|tbsp|English mustard|s;1|tbsp|Tomato ketchup|s;1|tsp|Cayenne pepper|s;2|tbsp|Honey|s;300|g|Potatoes|v', 'Mix sauce, mustard, ketchup, cayenne and honey into a marinade || Coat the chicken and leave 30 min if you can || Roast at 200C for 30-35 min, basting once || Serve with potatoes or wedges and salad'],
    ['chicken-wings', 'Chicken wings', 'Meat', 'Dinner', 45, 'Easy', 640, 40, 20, 42, '12||Chicken wings|m;1|tbsp|Baking powder|t;2|tbsp|Hot sauce|s;1|tbsp|Butter|d;2||Corn on the cob|v;1||Salad bag|v', 'Dry the wings and toss in baking powder, salt and pepper || Bake at 220C for 40-45 min, turning halfway || Toss in melted butter and hot sauce || Serve with corn and salad'],
    ['jerk-chicken', 'Jerk chicken', 'Meat', 'Dinner', 45, 'Medium', 580, 45, 50, 18, '4||Chicken legs|m;3|tbsp|Jerk seasoning|s;150|g|Rice|t;1||Tin kidney beans|t;1||Lime|v;1|tbsp|Oil|t', 'Rub chicken with jerk seasoning and oil, marinade if time allows || Roast at 200C for 40 min || Cook rice and beans together || Squeeze lime over and serve'],
    ['kebabs', 'Kebabs (chicken, lamb or beef)', 'Meat', 'Dinner', 30, 'Easy', 550, 42, 40, 22, '400|g|Chicken, lamb or beef chunks|m;2||Peppers|v;1||Red onion|v;2|tbsp|Kebab or fajita seasoning|s;2||Flatbreads|b;1|tbsp|Yoghurt|d', 'Toss meat in seasoning and yoghurt || Thread onto skewers with pepper and onion || Grill or barbecue 10-12 min, turning || Serve in warmed flatbreads with salad'],
    ['chicken-skewers', 'Chicken skewers', 'Meat', 'Dinner', 30, 'Easy', 480, 44, 36, 14, '2||Chicken breasts|m;1||Lemon|v;2|tbsp|Olive oil|t;1|tsp|Paprika|s;150|g|Couscous|t;1||Cucumber|v', 'Cube the chicken and marinate in oil, lemon, paprika, salt || Thread onto skewers || Grill 12 min, turning || Serve on couscous with chopped cucumber'],

    // ---------- PASTAS ----------
    ['carbonara', 'Spaghetti carbonara', 'Pastas', 'Dinner', 25, 'Easy', 720, 32, 80, 30, '200|g|Spaghetti|t;150|g|Pancetta or bacon|m;3||Eggs|d;50|g|Parmesan|d;2||Garlic cloves|v', 'Boil spaghetti, keep a cup of the water || Fry pancetta until crisp || Mix eggs and parmesan with lots of pepper || Toss hot pasta with pancetta, take off the heat, stir in egg mix with a splash of water until glossy'],
    ['bolognese', 'Spaghetti bolognese', 'Pastas', 'Dinner', 45, 'Easy', 690, 38, 78, 24, '300|g|Beef mince|m;200|g|Spaghetti|t;1||Onion|v;2||Carrots|v;1||Tin chopped tomatoes|t;2|tbsp|Tomato purée|t;2||Garlic cloves|v;1|tsp|Mixed herbs|s', 'Fry onion and carrot until soft, add garlic || Brown the mince, stir in purée || Add tomatoes and herbs, simmer 30 min || Cook spaghetti and serve topped with the sauce'],
    ['tomato-pasta', 'Tomato pasta', 'Pastas', 'Dinner', 20, 'Easy', 520, 16, 90, 10, '200|g|Pasta|t;1||Tin chopped tomatoes|t;2||Garlic cloves|v;1||Onion|v;1|tsp|Dried basil|s;30|g|Parmesan|d', 'Soften onion and garlic in oil || Add tomatoes and basil, simmer 15 min || Cook pasta, toss through the sauce || Top with parmesan'],
    ['meatball-pasta', 'Meatballs in tomato sauce', 'Pastas', 'Dinner', 40, 'Medium', 700, 36, 76, 28, '12||Beef meatballs|m;200|g|Spaghetti|t;1||Tin chopped tomatoes|t;1||Onion|v;2||Garlic cloves|v;1|tsp|Mixed herbs|s;30|g|Parmesan|d', 'Brown the meatballs in a pan || Add onion and garlic, then tomatoes and herbs || Simmer 20 min until cooked through || Serve over spaghetti with parmesan'],
    ['mac-n-cheese', 'Mac n cheese (bacon, sweetcorn, peas & broccoli)', 'Pastas', 'Dinner', 35, 'Easy', 820, 34, 78, 40, '200|g|Macaroni|t;150|g|Bacon|m;200|g|Cheddar|d;400|ml|Milk|d;25|g|Butter|d;25|g|Plain flour|t;100|g|Sweetcorn|f;100|g|Peas|f;1||Broccoli|v', 'Boil macaroni, adding broccoli for the last 3 min || Fry bacon until crisp || Make a roux with butter and flour, whisk in milk, stir in cheese || Combine with pasta, bacon, sweetcorn and peas, heat through'],
    ['lasagne', 'Lasagne', 'Pastas', 'Dinner', 75, 'Medium', 780, 40, 60, 40, '400|g|Beef mince|m;1||Pack lasagne sheets|t;1||Tin chopped tomatoes|t;500|ml|White sauce|d;150|g|Cheddar or mozzarella|d;1||Onion|v;2||Garlic cloves|v;1|tsp|Mixed herbs|s', 'Make a mince and tomato sauce (as bolognese) || Layer sauce, pasta sheets and white sauce in a dish || Top with cheese || Bake at 180C for 40 min until bubbling'],
    ['pesto-pasta', 'Pesto pasta', 'Pastas', 'Dinner', 20, 'Easy', 640, 26, 76, 24, '200|g|Pasta|t;4|tbsp|Green pesto|s;2||Chicken breasts|m;100|g|Cherry tomatoes|v;30|g|Parmesan|d', 'Cook pasta || Fry sliced chicken until cooked, add tomatoes || Toss with pesto and a splash of pasta water || Top with parmesan'],
    ['sundried-tomato-pasta', 'Sundried tomato pasta', 'Pastas', 'Dinner', 25, 'Easy', 660, 22, 78, 28, '200|g|Pasta|t;100|g|Sundried tomatoes|t;150|ml|Double cream|d;2||Garlic cloves|v;1||Bag spinach|v;30|g|Parmesan|d', 'Cook pasta || Fry garlic and chopped sundried tomatoes || Add cream and spinach, wilt down || Toss through pasta and add parmesan'],
    ['prawn-tomato-pasta', 'Prawn & tomato pasta', 'Pastas', 'Dinner', 25, 'Easy', 560, 34, 72, 12, '200|g|Pasta|t;200|g|Raw king prawns|m;1||Tin chopped tomatoes|t;2||Garlic cloves|v;1|tsp|Chilli flakes|s;1||Lemon|v', 'Cook pasta || Fry garlic and chilli, add tomatoes and simmer 10 min || Add prawns for 3-4 min until pink || Toss through pasta with lemon juice'],

    // ---------- PASTA BAKE ----------
    ['cheesy-conchiglie-bake', 'Cheesy conchiglie pasta bake', 'Pasta bake', 'Dinner', 45, 'Easy', 760, 30, 82, 34, '250|g|Conchiglie pasta|t;1||Tin chopped tomatoes|t;200|g|Cheddar|d;150|ml|Double cream|d;2||Garlic cloves|v;1||Onion|v;1|tsp|Mixed herbs|s', 'Cook pasta until just short of done || Make a quick tomato, onion, garlic and cream sauce || Mix with pasta in a dish, top with lots of cheese || Bake at 190C for 20-25 min until golden'],
    ['chicken-chorizo-bake', 'Chicken & chorizo pasta bake', 'Pasta bake', 'Dinner', 45, 'Easy', 800, 44, 76, 36, '250|g|Penne|t;2||Chicken breasts|m;100|g|Chorizo|m;1||Tin chopped tomatoes|t;150|g|Mozzarella|d;1||Onion|v;2||Garlic cloves|v', 'Fry chorizo and chopped chicken until cooked || Add onion, garlic and tomatoes, simmer 10 min || Mix with cooked penne, top with mozzarella || Bake at 190C for 20 min'],
    ['creamy-spinach-tomato-bake', 'Creamy spinach & tomato pasta bake', 'Pasta bake', 'Dinner', 40, 'Easy', 700, 26, 80, 28, '250|g|Pasta|t;1||Tin chopped tomatoes|t;2||Bags spinach|v;150|g|Cream cheese|d;150|g|Mozzarella|d;2||Garlic cloves|v', 'Cook pasta || Simmer tomatoes and garlic, stir in cream cheese and spinach || Mix with pasta, top with mozzarella || Bake at 190C for 20 min'],

    // ---------- BURGERS ----------
    ['chicken-burger', 'Chicken burger (buttermilk or peri peri)', 'Burgers', 'Dinner', 35, 'Medium', 780, 46, 70, 32, '2||Chicken breasts|m;150|ml|Buttermilk|d;100|g|Panko breadcrumbs|t;2||Brioche buns|b;1||Little gem lettuce|v;2|tbsp|Mayonnaise|s;1|tbsp|Peri peri seasoning|s;300|g|Oven chips|f', 'Butterfly the chicken and marinate in buttermilk (or peri peri) || Coat in seasoned panko || Bake or air fry at 200C for 20 min until crisp and cooked || Assemble in buns with lettuce and mayo, serve with chips'],
    ['halloumi-burger', 'Halloumi burger', 'Burgers', 'Dinner', 20, 'Easy', 690, 26, 62, 36, '1|block|Halloumi|d;2||Brioche buns|b;1||Little gem lettuce|v;1||Tomato|v;2|tbsp|Sweet chilli sauce|s;300|g|Oven chips|f', 'Slice halloumi and fry 2 min per side until golden || Toast the buns || Layer lettuce, tomato, halloumi and sweet chilli || Serve with chips'],
    ['beef-burger', 'Beef burger', 'Burgers', 'Dinner', 25, 'Easy', 850, 46, 60, 46, '400|g|Beef mince|m;2||Brioche buns|b;2||Cheese slices|d;1||Little gem lettuce|v;1||Tomato|v;1||Onion|v;300|g|Oven chips|f', 'Season mince and shape into 2 patties || Fry or grill 4-5 min per side, add cheese at the end || Toast buns || Build with lettuce, tomato and onion, serve with chips'],

    // ---------- CURRIES ----------
    ['tikka-masala', 'Chicken tikka masala', 'Curries', 'Dinner', 45, 'Medium', 640, 44, 60, 24, '3||Chicken thighs|m;3|tbsp|Tikka paste|s;1||Tin chopped tomatoes|t;100|ml|Double cream|d;1||Onion|v;150|g|Basmati rice|t;1|tbsp|Yoghurt|d', 'Marinate chicken in tikka paste and yoghurt if you have time || Fry onion, add chicken and brown || Add tomatoes, simmer 20 min, stir in cream || Serve with rice'],
    ['butter-chicken', 'Butter chicken', 'Curries', 'Dinner', 45, 'Medium', 670, 44, 58, 28, '3||Chicken thighs|m;2|tbsp|Butter chicken paste|s;1||Tin chopped tomatoes|t;100|ml|Double cream|d;1||Onion|v;2||Garlic cloves|v;150|g|Basmati rice|t;1|tbsp|Butter|d', 'Fry onion and garlic in butter || Add paste and chicken, brown || Add tomatoes and simmer 20 min, finish with cream || Serve with rice'],
    ['rogan-josh', 'Lamb rogan josh', 'Curries', 'Dinner', 120, 'Medium', 690, 42, 56, 32, '400|g|Diced lamb|m;3|tbsp|Rogan josh paste|s;1||Tin chopped tomatoes|t;2||Onions|v;150|g|Basmati rice|t;2||Garlic cloves|v;1|tbsp|Yoghurt|d', 'Brown the lamb in batches || Fry onions and garlic, add paste || Return lamb, add tomatoes and a splash of water || Simmer gently for 1.5 hours until tender, serve with rice'],
    ['thai-curry', 'Thai curry (green or red)', 'Curries', 'Dinner', 30, 'Easy', 600, 36, 52, 26, '2||Chicken breasts|m;3|tbsp|Thai green or red curry paste|s;1||Tin coconut milk|t;150|g|Jasmine rice|t;1||Pepper|v;100|g|Green beans|v;1|tbsp|Fish sauce|s', 'Fry the curry paste for 1 min, add chicken || Pour in coconut milk, simmer 10 min || Add pepper and beans, cook 5 min, season with fish sauce || Serve with rice'],

    // ---------- ASIAN ----------
    ['katsu-curry', 'Katsu curry', 'Asian', 'Dinner', 40, 'Medium', 780, 42, 88, 26, '2||Chicken breasts|m;1|pack|Katsu curry sauce|s;100|g|Panko breadcrumbs|t;1||Egg|d;30|g|Plain flour|t;150|g|Rice|t', 'Flatten chicken, coat in flour, egg then panko || Bake at 200C for 25 min or shallow fry || Heat the katsu sauce and cook the rice || Slice chicken and serve over rice with sauce'],
    ['porky-noodles', 'Porky noodles', 'Asian', 'Dinner', 25, 'Easy', 620, 34, 68, 22, '300|g|Pork mince|m;2||Nests noodles|t;2|tbsp|Soy sauce|s;1|tbsp|Hoisin|s;2||Garlic cloves|v;2||Spring onions|v;1||Carrot|v', 'Cook the noodles || Fry pork mince until browned, add garlic and grated carrot || Stir in soy and hoisin || Toss with noodles and top with spring onion'],
    ['sticky-pork-rice', 'Sticky pork with rice', 'Asian', 'Dinner', 30, 'Easy', 650, 36, 70, 24, '300|g|Diced pork|m;3|tbsp|Honey|s;2|tbsp|Soy sauce|s;1|tbsp|Sweet chilli sauce|s;150|g|Rice|t;1||Pak choi|v;2||Garlic cloves|v', 'Fry pork until browned || Add garlic, honey, soy and chilli sauce, bubble until sticky || Cook rice and steam the pak choi || Serve together'],
    ['chilli-chicken-ramen', 'Chilli chicken ramen', 'Asian', 'Dinner', 30, 'Easy', 560, 40, 62, 16, '2||Chicken breasts|m;2||Nests ramen noodles|t;700|ml|Chicken stock|t;1|tbsp|Chilli paste|s;2||Eggs|d;1||Pak choi|v;2||Spring onions|v', 'Simmer stock with chilli paste || Add sliced chicken, cook 8 min || Add noodles and pak choi for 3 min || Top with soft boiled egg and spring onion'],

    // ---------- STIR FRY ----------
    ['beef-broccoli', 'Beef & broccoli', 'Stir fry', 'Dinner', 25, 'Easy', 540, 40, 50, 18, '300|g|Beef strips|m;1||Broccoli|v;3|tbsp|Soy sauce|s;1|tbsp|Oyster sauce|s;1|tsp|Cornflour|t;150|g|Rice|t;2||Garlic cloves|v', 'Toss beef in cornflour, fry hot and fast, set aside || Stir fry broccoli and garlic || Add soy and oyster sauce with a splash of water || Return beef, cook 1 min, serve with rice'],
    ['chilli-garlic-prawns', 'Chilli garlic prawns', 'Stir fry', 'Dinner', 20, 'Easy', 430, 34, 46, 12, '250|g|Raw king prawns|m;3||Garlic cloves|v;1||Red chilli|v;2|tbsp|Soy sauce|s;150|g|Rice|t;1||Pepper|v;1||Lime|v', 'Cook rice || Stir fry garlic, chilli and pepper for 2 min || Add prawns for 3 min until pink || Add soy and lime, serve over rice'],
    ['peanut-stir-fry', 'Peanut stir fry', 'Stir fry', 'Dinner', 25, 'Easy', 610, 32, 62, 26, '2||Chicken breasts|m;3|tbsp|Peanut butter|t;2|tbsp|Soy sauce|s;1|pack|Stir fry veg|v;2||Nests noodles|t;1||Lime|v', 'Cook noodles || Stir fry chicken, add veg || Mix peanut butter, soy, lime and a splash of hot water, pour in || Toss with noodles'],
    ['chilli-beef', 'Chilli beef', 'Stir fry', 'Dinner', 25, 'Easy', 580, 40, 54, 22, '300|g|Beef strips|m;1||Pepper|v;1||Onion|v;2|tbsp|Sweet chilli sauce|s;2|tbsp|Soy sauce|s;150|g|Rice|t;1||Red chilli|v', 'Cook rice || Stir fry beef hot and fast, set aside || Fry pepper, onion and chilli || Return beef with sauces and serve on rice'],

    // ---------- SOUPS ----------
    ['butternut-soup', 'Butternut squash soup', 'Soups', 'Dinner', 45, 'Easy', 330, 8, 48, 12, '1||Butternut squash|v;1||Onion|v;600|ml|Vegetable stock|t;2||Garlic cloves|v;50|ml|Cream|d;1||Crusty loaf|b', 'Roast cubed squash at 200C for 30 min || Soften onion and garlic || Add squash and stock, simmer 10 min, blend || Stir in cream and serve with bread'],
    ['chicken-soup', 'Chicken soup', 'Soups', 'Dinner', 45, 'Easy', 380, 34, 30, 12, '2||Chicken breasts|m;2||Carrots|v;2||Celery sticks|v;1||Onion|v;800|ml|Chicken stock|t;1||Crusty loaf|b', 'Soften onion, carrot and celery || Add stock and chicken, simmer 20 min || Remove chicken, shred and return || Serve with bread'],
    ['chicken-noodle-soup', 'Chicken noodle soup', 'Soups', 'Dinner', 30, 'Easy', 420, 32, 46, 10, '2||Chicken breasts|m;2||Nests noodles|t;800|ml|Chicken stock|t;2||Carrots|v;1||Leek|v;2||Garlic cloves|v', 'Simmer stock with garlic, carrots and leek || Poach chicken 15 min, shred || Add noodles for 4 min || Return chicken and season'],

    // ---------- PIES & PASTRY ----------
    ['chicken-pie', 'Chicken pie', 'Pies & pastry', 'Dinner', 60, 'Medium', 780, 40, 56, 44, '3||Chicken breasts|m;1||Leek|v;1||Onion|v;200|ml|Chicken stock|t;100|ml|Double cream|d;1|sheet|Puff pastry|d;1||Egg|d', 'Fry onion, leek and chicken chunks || Add stock and cream, simmer until thick || Put in a dish, cover with pastry and brush with egg || Bake at 200C for 30 min until golden'],
    ['chicken-bacon-pie', 'Chicken & bacon pie', 'Pies & pastry', 'Dinner', 60, 'Medium', 820, 42, 54, 48, '3||Chicken breasts|m;150|g|Bacon|m;1||Leek|v;200|ml|Chicken stock|t;100|ml|Double cream|d;1|sheet|Puff pastry|d;1||Egg|d', 'Fry bacon, leek and chicken || Add stock and cream, simmer until thick || Top with pastry and egg wash || Bake at 200C for 30 min'],
    ['salmon-pastry', 'Salmon, cream cheese & broccoli pastry', 'Pies & pastry', 'Dinner', 40, 'Medium', 760, 36, 42, 46, '2||Salmon fillets|m;1|sheet|Puff pastry|d;100|g|Cream cheese|d;1||Broccoli|v;1||Lemon|v;1||Egg|d', 'Lay salmon on pastry, spread with cream cheese, add broccoli florets || Fold and seal, brush with egg || Bake at 200C for 25 min || Squeeze lemon over to serve'],

    // ---------- ROASTS & SIDES ----------
    ['roast-lamb', 'Roast lamb', 'Roasts', 'Dinner', 150, 'Medium', 820, 50, 50, 42, '1|small|Lamb leg or shoulder|m;600|g|Potatoes|v;3||Carrots|v;1||Broccoli|v;3||Garlic cloves|v;2|sprigs|Rosemary|v;1|pack|Gravy|t', 'Stud lamb with garlic and rosemary, season || Roast at 180C for about 2 hours || Roast potatoes and veg for the last hour || Rest 20 min, carve and serve with gravy'],
    ['roast-chicken', 'Roast chicken', 'Roasts', 'Dinner', 90, 'Easy', 700, 52, 44, 32, '1||Whole chicken|m;600|g|Potatoes|v;3||Carrots|v;1||Broccoli|v;1||Lemon|v;1|pack|Gravy|t;1|knob|Butter|d', 'Rub chicken with butter, salt and pepper, stuff with lemon || Roast at 190C for 1h15 || Roast potatoes and veg alongside || Rest 15 min, carve, serve with gravy'],
    ['roast-beef', 'Roast beef', 'Roasts', 'Dinner', 100, 'Medium', 790, 56, 46, 36, '1|joint|Beef joint|m;600|g|Potatoes|v;3||Carrots|v;1||Broccoli|v;1|pot|Horseradish|s;1|pack|Gravy|t', 'Season beef and sear all over || Roast at 190C, about 20 min per 500g for medium || Roast potatoes and veg || Rest 20 min, slice and serve with horseradish'],
    ['toad-in-the-hole', 'Toad in the hole', 'Roasts', 'Dinner', 50, 'Easy', 860, 32, 66, 48, '6||Sausages|m;100|g|Plain flour|t;2||Eggs|d;150|ml|Milk|d;1||Onion|v;300|g|Mash potato|v;1|pack|Onion gravy|t', 'Brown sausages in a hot tin at 220C for 10 min || Whisk batter of flour, eggs and milk || Pour over sausages in the hot tin || Bake 30 min until risen, serve with mash and gravy'],
    ['roast-gammon', 'Gammon', 'Roasts', 'Dinner', 120, 'Easy', 700, 56, 30, 34, '1|joint|Gammon joint|m;500|g|Potatoes|v;2||Eggs|d;150|g|Peas|f;1|jar|Pineapple or mustard|s', 'Simmer gammon in water for 1 hour || Glaze with mustard or honey and roast 30 min at 190C || Fry eggs, cook potatoes and peas || Slice and serve'],
    ['honey-ham', 'Ham (honey glazed)', 'Roasts', 'Dinner', 120, 'Easy', 680, 54, 32, 32, '1|joint|Ham joint|m;4|tbsp|Honey|s;2|tbsp|Wholegrain mustard|s;600|g|Potatoes|v;150|g|Green beans|v', 'Simmer ham for 1 hour || Score, brush with honey and mustard || Roast at 190C for 30 min || Serve sliced with potatoes and beans'],

    // ---------- SIDES ----------
    ['yorkshire-pudding', 'Yorkshire pudding', 'Roasts', 'Side', 30, 'Easy', 150, 5, 18, 6, '100|g|Plain flour|t;2||Eggs|d;150|ml|Milk|d;4|tbsp|Oil|t', 'Heat oil in a muffin tin at 220C || Whisk flour, eggs and milk into a batter || Pour into the hot tin || Bake 20 min until puffed and golden'],
    ['bread-sauce', 'Bread sauce', 'Roasts', 'Side', 20, 'Easy', 120, 4, 14, 5, '1||Onion|v;4||Cloves|s;300|ml|Milk|d;60|g|Breadcrumbs|b;20|g|Butter|d', 'Stud onion with cloves, simmer in milk for 10 min || Remove onion, stir in breadcrumbs || Cook until thick, add butter and season'],
    ['apple-sauce', 'Apple sauce', 'Roasts', 'Side', 15, 'Easy', 60, 0, 15, 0, '3||Bramley apples|v;2|tbsp|Sugar|t;2|tbsp|Water|o', 'Peel and chop apples || Simmer with sugar and water for 10 min || Mash to your preferred texture'],
    ['cauliflower-cheese', 'Cauliflower cheese', 'Roasts', 'Side', 40, 'Easy', 320, 14, 14, 22, '1||Cauliflower|v;25|g|Butter|d;25|g|Plain flour|t;300|ml|Milk|d;120|g|Cheddar|d', 'Boil cauliflower for 5 min, drain || Make a roux, whisk in milk, stir in most of the cheese || Pour over cauliflower in a dish, top with the rest || Bake at 200C for 20 min'],

    // ---------- MEXICAN ----------
    ['soft-tacos', 'Soft shell tacos', 'Mexican', 'Dinner', 25, 'Easy', 640, 34, 62, 26, '300|g|Beef mince|m;1|pack|Taco seasoning|s;4||Soft tortillas|b;1||Little gem lettuce|v;1||Tomato|v;80|g|Cheddar|d;2|tbsp|Soured cream|d', 'Brown the mince and stir in taco seasoning with a splash of water || Warm the tortillas || Fill with mince, lettuce, tomato, cheese and soured cream'],
    ['hard-tacos', 'Hard shell tacos', 'Mexican', 'Dinner', 25, 'Easy', 620, 34, 56, 28, '300|g|Chicken or beef mince|m;1|pack|Taco seasoning|s;6||Taco shells|b;1||Tomato|v;1||Little gem lettuce|v;80|g|Cheddar|d;1||Avocado|v', 'Cook mince with taco seasoning || Warm the shells in the oven for 3 min || Fill with meat, lettuce, tomato, cheese and avocado'],
    ['burritos', 'Burritos', 'Mexican', 'Dinner', 30, 'Easy', 760, 38, 84, 26, '300|g|Chicken or beef|m;2||Large tortillas|b;150|g|Rice|t;1||Tin black beans|t;1|pack|Fajita seasoning|s;80|g|Cheddar|d;2|tbsp|Soured cream|d', 'Cook rice || Fry meat with seasoning, add beans || Fill tortillas with rice, meat, cheese and soured cream || Roll up and toast in a pan 1 min each side'],
    ['fajitas', 'Fajitas', 'Mexican', 'Dinner', 25, 'Easy', 590, 40, 58, 20, '2||Chicken breasts|m;2||Peppers|v;1||Onion|v;1|pack|Fajita seasoning|s;4||Tortillas|b;80|g|Cheddar|d;2|tbsp|Soured cream|d', 'Slice chicken, peppers and onion || Fry chicken, add veg and seasoning, cook 8 min || Warm the tortillas || Fill and top with cheese and soured cream'],
    ['chilli-con-carne', 'Chilli con carne', 'Mexican', 'Dinner', 50, 'Easy', 640, 40, 62, 24, '300|g|Beef mince|m;1||Tin kidney beans|t;1||Tin chopped tomatoes|t;1||Onion|v;1||Pepper|v;1|pack|Chilli seasoning|s;150|g|Rice|t', 'Fry onion and pepper, brown mince || Add seasoning, tomatoes and beans || Simmer 30 min || Serve with rice'],
    ['empanadas', 'Empanadas', 'Mexican', 'Dinner', 50, 'Medium', 700, 26, 64, 36, '250|g|Beef mince|m;1||Onion|v;1||Egg|d;1|pack|Shortcrust pastry rounds or sheet|d;1|tsp|Cumin|s;80|g|Cheddar|d;1||Salad bag|v', 'Fry onion and mince with cumin, cool || Cut pastry into rounds, fill, add cheese, fold and crimp || Brush with egg || Bake at 200C for 25 min and serve with salad'],
    ['enchiladas', 'Enchiladas', 'Mexican', 'Dinner', 45, 'Medium', 740, 38, 70, 32, '300|g|Chicken or beef|m;4||Tortillas|b;1||Tin enchilada sauce or chopped tomatoes|t;150|g|Cheddar|d;1||Pepper|v;1||Onion|v', 'Fry meat, pepper and onion || Fill and roll tortillas, place seam down in a dish || Pour over sauce and top with cheese || Bake at 190C for 20 min'],

    // ---------- FISH ----------
    ['breaded-fish', 'Breaded fish & potato', 'Fish', 'Dinner', 35, 'Easy', 640, 36, 68, 24, '2||Breaded fish fillets|m;500|g|Potatoes|v;150|g|Peas|f;1||Lemon|v;2|tbsp|Tartare sauce|s', 'Cut potatoes into chips and roast at 220C for 35 min || Bake fish for the last 20 min || Boil peas || Serve with lemon and tartare sauce'],
    ['grilled-salmon', 'Grilled salmon', 'Fish', 'Dinner', 25, 'Easy', 520, 38, 30, 28, '2||Salmon fillets|m;250|g|New potatoes|v;150|g|Tenderstem broccoli|v;1||Lemon|v;1|tbsp|Olive oil|t', 'Boil potatoes || Season salmon with oil and lemon, grill 8-10 min || Steam the broccoli || Serve together'],
    ['breaded-salmon', 'Breaded salmon', 'Fish', 'Dinner', 30, 'Easy', 640, 40, 44, 32, '2||Salmon fillets|m;60|g|Panko breadcrumbs|t;1|tbsp|Dijon mustard|s;300|g|Potatoes|v;150|g|Green beans|v;1||Lemon|v', 'Brush salmon with mustard and press in panko || Bake at 200C for 15-18 min || Boil potatoes and beans || Serve with lemon'],

    // ---------- PIZZA ----------
    ['homemade-pizza', 'Homemade pizza', 'Pizza', 'Dinner', 40, 'Easy', 800, 32, 90, 32, '2||Pizza bases or dough balls|b;150|ml|Passata|t;200|g|Mozzarella|d;1|pack|Pepperoni or toppings|m;1||Pepper|v;1|tsp|Dried oregano|s', 'Heat the oven to its highest setting || Spread passata on bases || Add mozzarella and toppings || Bake 10-12 min until bubbling'],

    // ---------- EUROPEAN ----------
    ['chicken-souvlaki', 'Chicken souvlaki', 'European', 'Dinner', 35, 'Easy', 610, 44, 56, 22, '2||Chicken breasts|m;1||Lemon|v;2|tbsp|Olive oil|t;2|tsp|Dried oregano|s;4||Pitta breads|b;2|tbsp|Tzatziki|d;1||Cucumber|v;1||Tomato|v', 'Marinate cubed chicken in lemon, oil, oregano and garlic || Thread on skewers and grill 12 min || Warm the pittas || Fill with chicken, salad and tzatziki'],
    ['mezze', 'Mezze', 'European', 'Dinner', 20, 'Easy', 700, 24, 68, 38, '1|tub|Hummus|d;1|pack|Falafel|f;4||Pitta breads|b;1||Cucumber|v;100|g|Feta|d;1|jar|Olives|t;1|tub|Tzatziki|d;2||Tomatoes|v', 'Warm the falafel and pittas || Slice cucumber and tomatoes || Lay everything out on a board to share'],
  ];

  function parseIngs(s) {
    return s.split(';').map(function (x) {
      var p = x.split('|');
      return { name: p[2], qty: p[0] === '' ? 0 : parseFloat(p[0]), unit: p[1] || '', aisle: AISLE[p[3]] || 'Other' };
    });
  }
  var out = rows.map(function (r) {
    return {
      id: 'starter-' + r[0], name: r[1], cuisine: r[2], type: r[3], time: r[4], difficulty: r[5],
      macros: { cal: r[6], protein: r[7], carbs: r[8], fat: r[9] },
      ingredients: parseIngs(r[10]), steps: r[11].split(' || '),
      serves: 2, fav: false, photo: '', starter: true
    };
  });
  window.DP_SEED = out;
  window.DP_AISLES = ['Fruit & veg', 'Meat & fish', 'Dairy & eggs', 'Bakery', 'Tins & dry', 'Spices & sauces', 'Frozen', 'Other'];
  window.DP_DEFAULT_CUISINES = ['Meat', 'Pastas', 'Pasta bake', 'Burgers', 'Curries', 'Asian', 'Stir fry', 'Soups', 'Pies & pastry', 'Roasts', 'Mexican', 'Fish', 'Pizza', 'European'];
  window.DP_DEFAULT_TYPES = ['Dinner', 'Side', 'Dessert'];
})();
